<?php


/**
 * Render entity attributes to html.
 */
function entity_attributes_html(Drupal\Core\Entity\Entity $entity)
{
  $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();
}

/**
 * Implements hook_entity_view().
 */
function entity_attributes_entity_view(
    array &$build,
    \Drupal\Core\Entity\EntityInterface $entity,
    \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display,
    $view_mode
)
{
    $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();
    $entityAttributes = $entityAttributesHelper->getEntityAttributes($entity);

    if (!empty($entityAttributes)) {
        $build['#entity_attributes'] = $entityAttributes;
    }
}

/**
 * Implements hook_preprocess().
 */
function entity_attributes_preprocess(&$variables, $hook)
{
    $entityAttributes = [];

    $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();

    if (isset($variables['elements']['#entity_attributes'])) {
        $entityAttributes = $variables['elements']['#entity_attributes'];
    }

    if (isset($variables['elements']['content']['#entity_attributes'])) {
        $entityAttributes = $variables['elements']['content']['#entity_attributes'];
    }

    if ($hook == 'ds_entity_view' && isset($variables['content']['#entity'])) {
      $entityAttributes = $entityAttributesHelper->getEntityAttributes($variables['content']['#entity']);
    }

    if (!empty($entityAttributes)) {
        if (!isset($variables['attributes'])) {
            $variables['attributes'] = [];
        }
        $variables['attributes'] = array_merge_recursive($variables['attributes'], $entityAttributes);
    }

}

/**
 * Implements hook_ds_pre_render_alter().
 */
function entity_attributes_ds_pre_render_alter(array &$layout_render_array, array $context, array &$variables)
{
    $entity = $context['entity'];

    $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();
    $entityAttributes = $entityAttributesHelper->getEntityAttributes($entity);

    if (!empty($entityAttributes)) {
        $variables['attributes'] = array_merge_recursive($variables['attributes'], $entityAttributes);
    }
}

function entity_attributes_preprocess_field__ds_field_expert(&$variables)
{
    $entity = $variables['element']['#object'];

    $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();
    $entityAttributes = $entityAttributesHelper->getEntityAttributes($entity);

    $attributeMapping = [
        'lbw-at' => 'label_attributes',
        'ow-at' => 'wrapper_attributes',
        'fis-at' => 'field_wrapper_attributes',
        'fi-at' => 'field_item_wrapper_attributes',
    ];

    foreach ($attributeMapping as $settingName => $attributeField) {
        if (strpos($variables['settings'][$settingName], '{{entity_attributes}}') !== false) {
            $variables['settings'][$settingName] = str_replace(
                '{{entity_attributes}}',
                '',
                $variables['settings'][$settingName]
            );

            if (!empty($entityAttributes)) {
                $variables[$attributeField]->mergeAttributes(new \Drupal\ds\DsAttribute($entityAttributes));
            }
        }
    }

}

function entity_attributes_field_group_pre_render_alter(&$element, $group, $rendering_object)
{

  if (!isset($rendering_object['#entity'])) {
    return null;
  }

  $entity = $rendering_object['#entity'];

  $entityAttributesHelper = new \Drupal\entity_attributes\Helper\EntityAttributesHelper();
  $entityAttributes = $entityAttributesHelper->getEntityAttributes($entity);

  if ($group->format_type == 'html_element' && !empty($group->format_settings['attributes'])) {
    if ($element['#attributes'] && strpos('{{entity_attributes}}', $group->format_settings['attributes']) !== false) {
      $attributeArray = $entityAttributes;
      $originalAttributes = $element['#attributes']->toArray();
      $mergedAttributes = array_merge_recursive($attributeArray, $originalAttributes);

      $element['#attributes'] = new \Drupal\Core\Template\Attribute($mergedAttributes);
    }
  }
}

/**
 * Implements hook_editor_js_settings_alter()
 * @param array $settings
 */
function sarco_site_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as $name => $value) {
    $settings['editor']['formats'][$name]['editorSettings']['autoParagraph'] = FALSE;
  }
}
